// <auto-generated />
using System;
using AgenciaDeDavid.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AgenciadeDavid.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250806202753_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AgenciaDeDavid.Models.Destino", b =>
                {
                    b.Property<int>("DestinoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DestinoID"));

                    b.Property<string>("Ciudad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan>("Duracion")
                        .HasColumnType("time");

                    b.Property<string>("LugarTuristico")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("PaisID")
                        .HasColumnType("int");

                    b.HasKey("DestinoID");

                    b.HasIndex("PaisID");

                    b.ToTable("Destinos");

                    b.HasData(
                        new
                        {
                            DestinoID = 1,
                            Ciudad = "Punta Cana",
                            Duracion = new TimeSpan(0, 0, 0, 0, 0),
                            LugarTuristico = "Playa Bávaro",
                            Nombre = "Punta Cana",
                            PaisID = 1
                        },
                        new
                        {
                            DestinoID = 2,
                            Ciudad = "Cancún",
                            Duracion = new TimeSpan(0, 0, 0, 0, 0),
                            LugarTuristico = "Zona Hotelera",
                            Nombre = "Cancún",
                            PaisID = 2
                        },
                        new
                        {
                            DestinoID = 3,
                            Ciudad = "Orlando",
                            Duracion = new TimeSpan(0, 0, 0, 0, 0),
                            LugarTuristico = "Disney World",
                            Nombre = "Orlando",
                            PaisID = 3
                        },
                        new
                        {
                            DestinoID = 4,
                            Ciudad = "Barcelona",
                            Duracion = new TimeSpan(0, 0, 0, 0, 0),
                            LugarTuristico = "Sagrada Familia",
                            Nombre = "Barcelona",
                            PaisID = 4
                        },
                        new
                        {
                            DestinoID = 5,
                            Ciudad = "París",
                            Duracion = new TimeSpan(0, 0, 0, 0, 0),
                            LugarTuristico = "Torre Eiffel",
                            Nombre = "París",
                            PaisID = 5
                        },
                        new
                        {
                            DestinoID = 6,
                            Ciudad = "Roma",
                            Duracion = new TimeSpan(0, 0, 0, 0, 0),
                            LugarTuristico = "Coliseo Romano",
                            Nombre = "Roma",
                            PaisID = 6
                        },
                        new
                        {
                            DestinoID = 7,
                            Ciudad = "Tokio",
                            Duracion = new TimeSpan(0, 0, 0, 0, 0),
                            LugarTuristico = "Shibuya",
                            Nombre = "Tokio",
                            PaisID = 7
                        },
                        new
                        {
                            DestinoID = 8,
                            Ciudad = "Río de Janeiro",
                            Duracion = new TimeSpan(0, 0, 0, 0, 0),
                            LugarTuristico = "Cristo Redentor",
                            Nombre = "Río de Janeiro",
                            PaisID = 8
                        },
                        new
                        {
                            DestinoID = 9,
                            Ciudad = "Bangkok",
                            Duracion = new TimeSpan(0, 0, 0, 0, 0),
                            LugarTuristico = "Templo Wat Arun",
                            Nombre = "Bangkok",
                            PaisID = 9
                        },
                        new
                        {
                            DestinoID = 10,
                            Ciudad = "El Cairo",
                            Duracion = new TimeSpan(0, 0, 0, 0, 0),
                            LugarTuristico = "Pirámides de Giza",
                            Nombre = "El Cairo",
                            PaisID = 10
                        },
                        new
                        {
                            DestinoID = 11,
                            Ciudad = "Buenos Aires",
                            Duracion = new TimeSpan(0, 0, 0, 0, 0),
                            LugarTuristico = "Barrio La Boca",
                            Nombre = "Buenos Aires",
                            PaisID = 11
                        },
                        new
                        {
                            DestinoID = 12,
                            Ciudad = "Toronto",
                            Duracion = new TimeSpan(0, 0, 0, 0, 0),
                            LugarTuristico = "Torre CN",
                            Nombre = "Toronto",
                            PaisID = 12
                        },
                        new
                        {
                            DestinoID = 13,
                            Ciudad = "Berlín",
                            Duracion = new TimeSpan(0, 0, 0, 0, 0),
                            LugarTuristico = "Muro de Berlín",
                            Nombre = "Berlín",
                            PaisID = 13
                        },
                        new
                        {
                            DestinoID = 14,
                            Ciudad = "Sídney",
                            Duracion = new TimeSpan(0, 0, 0, 0, 0),
                            LugarTuristico = "Ópera de Sídney",
                            Nombre = "Sídney",
                            PaisID = 14
                        },
                        new
                        {
                            DestinoID = 15,
                            Ciudad = "Pekín",
                            Duracion = new TimeSpan(0, 0, 0, 0, 0),
                            LugarTuristico = "Ciudad Prohibida",
                            Nombre = "Pekín",
                            PaisID = 15
                        },
                        new
                        {
                            DestinoID = 16,
                            Ciudad = "Nueva Delhi",
                            Duracion = new TimeSpan(0, 0, 0, 0, 0),
                            LugarTuristico = "Templo de Loto",
                            Nombre = "Nueva Delhi",
                            PaisID = 16
                        },
                        new
                        {
                            DestinoID = 17,
                            Ciudad = "Atenas",
                            Duracion = new TimeSpan(0, 0, 0, 0, 0),
                            LugarTuristico = "Acrópolis",
                            Nombre = "Atenas",
                            PaisID = 17
                        },
                        new
                        {
                            DestinoID = 18,
                            Ciudad = "Ciudad del Cabo",
                            Duracion = new TimeSpan(0, 0, 0, 0, 0),
                            LugarTuristico = "Montaña de la Mesa",
                            Nombre = "Ciudad del Cabo",
                            PaisID = 18
                        },
                        new
                        {
                            DestinoID = 19,
                            Ciudad = "Cartagena",
                            Duracion = new TimeSpan(0, 0, 0, 0, 0),
                            LugarTuristico = "Ciudad Amurallada",
                            Nombre = "Cartagena",
                            PaisID = 19
                        },
                        new
                        {
                            DestinoID = 20,
                            Ciudad = "Cuzco",
                            Duracion = new TimeSpan(0, 0, 0, 0, 0),
                            LugarTuristico = "Machu Picchu",
                            Nombre = "Cuzco",
                            PaisID = 20
                        });
                });

            modelBuilder.Entity("AgenciaDeDavid.Models.Pais", b =>
                {
                    b.Property<int>("PaisID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaisID"));

                    b.Property<string>("Ciudad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("PaisID");

                    b.ToTable("Paises");

                    b.HasData(
                        new
                        {
                            PaisID = 1,
                            Ciudad = "Santo Domingo",
                            Nombre = "República Dominicana"
                        },
                        new
                        {
                            PaisID = 2,
                            Ciudad = "Ciudad de México",
                            Nombre = "México"
                        },
                        new
                        {
                            PaisID = 3,
                            Ciudad = "Washington D.C.",
                            Nombre = "Estados Unidos"
                        },
                        new
                        {
                            PaisID = 4,
                            Ciudad = "Madrid",
                            Nombre = "España"
                        },
                        new
                        {
                            PaisID = 5,
                            Ciudad = "París",
                            Nombre = "Francia"
                        },
                        new
                        {
                            PaisID = 6,
                            Ciudad = "Roma",
                            Nombre = "Italia"
                        },
                        new
                        {
                            PaisID = 7,
                            Ciudad = "Tokio",
                            Nombre = "Japón"
                        },
                        new
                        {
                            PaisID = 8,
                            Ciudad = "Brasilia",
                            Nombre = "Brasil"
                        },
                        new
                        {
                            PaisID = 9,
                            Ciudad = "Bangkok",
                            Nombre = "Tailandia"
                        },
                        new
                        {
                            PaisID = 10,
                            Ciudad = "El Cairo",
                            Nombre = "Egipto"
                        },
                        new
                        {
                            PaisID = 11,
                            Ciudad = "Buenos Aires",
                            Nombre = "Argentina"
                        },
                        new
                        {
                            PaisID = 12,
                            Ciudad = "Ottawa",
                            Nombre = "Canadá"
                        },
                        new
                        {
                            PaisID = 13,
                            Ciudad = "Berlín",
                            Nombre = "Alemania"
                        },
                        new
                        {
                            PaisID = 14,
                            Ciudad = "Canberra",
                            Nombre = "Australia"
                        },
                        new
                        {
                            PaisID = 15,
                            Ciudad = "Pekín",
                            Nombre = "China"
                        },
                        new
                        {
                            PaisID = 16,
                            Ciudad = "Nueva Delhi",
                            Nombre = "India"
                        },
                        new
                        {
                            PaisID = 17,
                            Ciudad = "Atenas",
                            Nombre = "Grecia"
                        },
                        new
                        {
                            PaisID = 18,
                            Ciudad = "Pretoria",
                            Nombre = "Sudáfrica"
                        },
                        new
                        {
                            PaisID = 19,
                            Ciudad = "Bogotá",
                            Nombre = "Colombia"
                        },
                        new
                        {
                            PaisID = 20,
                            Ciudad = "Lima",
                            Nombre = "Perú"
                        });
                });

            modelBuilder.Entity("AgenciaDeDavid.Models.Tour", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("DestinoID")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("HoraInicio")
                        .HasColumnType("time");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PaisID")
                        .HasColumnType("int");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("TourID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("DestinoID");

                    b.HasIndex("PaisID");

                    b.ToTable("Tours");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            DestinoID = 1,
                            FechaInicio = new DateTime(2025, 8, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HoraInicio = new TimeSpan(0, 9, 0, 0, 0),
                            Nombre = "Tour a Punta Cana",
                            PaisID = 1,
                            Precio = 250.00m,
                            TourID = 0
                        },
                        new
                        {
                            ID = 2,
                            DestinoID = 2,
                            FechaInicio = new DateTime(2025, 8, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HoraInicio = new TimeSpan(0, 8, 30, 0, 0),
                            Nombre = "Tour a Cancún",
                            PaisID = 2,
                            Precio = 300.00m,
                            TourID = 0
                        },
                        new
                        {
                            ID = 3,
                            DestinoID = 3,
                            FechaInicio = new DateTime(2025, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HoraInicio = new TimeSpan(0, 10, 0, 0, 0),
                            Nombre = "Tour a Orlando",
                            PaisID = 3,
                            Precio = 400.00m,
                            TourID = 0
                        },
                        new
                        {
                            ID = 4,
                            DestinoID = 4,
                            FechaInicio = new DateTime(2025, 8, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HoraInicio = new TimeSpan(0, 9, 15, 0, 0),
                            Nombre = "Tour a Barcelona",
                            PaisID = 4,
                            Precio = 350.00m,
                            TourID = 0
                        },
                        new
                        {
                            ID = 5,
                            DestinoID = 5,
                            FechaInicio = new DateTime(2025, 8, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HoraInicio = new TimeSpan(0, 9, 45, 0, 0),
                            Nombre = "Tour a París",
                            PaisID = 5,
                            Precio = 500.00m,
                            TourID = 0
                        },
                        new
                        {
                            ID = 6,
                            DestinoID = 6,
                            FechaInicio = new DateTime(2025, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HoraInicio = new TimeSpan(0, 8, 0, 0, 0),
                            Nombre = "Tour a Roma",
                            PaisID = 6,
                            Precio = 480.00m,
                            TourID = 0
                        },
                        new
                        {
                            ID = 7,
                            DestinoID = 7,
                            FechaInicio = new DateTime(2025, 8, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HoraInicio = new TimeSpan(0, 10, 30, 0, 0),
                            Nombre = "Tour a Tokio",
                            PaisID = 7,
                            Precio = 650.00m,
                            TourID = 0
                        },
                        new
                        {
                            ID = 8,
                            DestinoID = 8,
                            FechaInicio = new DateTime(2025, 8, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HoraInicio = new TimeSpan(0, 9, 0, 0, 0),
                            Nombre = "Tour a Río de Janeiro",
                            PaisID = 8,
                            Precio = 400.00m,
                            TourID = 0
                        },
                        new
                        {
                            ID = 9,
                            DestinoID = 9,
                            FechaInicio = new DateTime(2025, 8, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HoraInicio = new TimeSpan(0, 7, 45, 0, 0),
                            Nombre = "Tour a Bangkok",
                            PaisID = 9,
                            Precio = 550.00m,
                            TourID = 0
                        },
                        new
                        {
                            ID = 10,
                            DestinoID = 10,
                            FechaInicio = new DateTime(2025, 8, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HoraInicio = new TimeSpan(0, 8, 30, 0, 0),
                            Nombre = "Tour a El Cairo",
                            PaisID = 10,
                            Precio = 300.00m,
                            TourID = 0
                        },
                        new
                        {
                            ID = 11,
                            DestinoID = 11,
                            FechaInicio = new DateTime(2025, 8, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HoraInicio = new TimeSpan(0, 9, 15, 0, 0),
                            Nombre = "Tour a Buenos Aires",
                            PaisID = 11,
                            Precio = 270.00m,
                            TourID = 0
                        },
                        new
                        {
                            ID = 12,
                            DestinoID = 12,
                            FechaInicio = new DateTime(2025, 8, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HoraInicio = new TimeSpan(0, 10, 0, 0, 0),
                            Nombre = "Tour a Toronto",
                            PaisID = 12,
                            Precio = 320.00m,
                            TourID = 0
                        },
                        new
                        {
                            ID = 13,
                            DestinoID = 13,
                            FechaInicio = new DateTime(2025, 8, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HoraInicio = new TimeSpan(0, 9, 45, 0, 0),
                            Nombre = "Tour a Berlín",
                            PaisID = 13,
                            Precio = 400.00m,
                            TourID = 0
                        },
                        new
                        {
                            ID = 14,
                            DestinoID = 14,
                            FechaInicio = new DateTime(2025, 8, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HoraInicio = new TimeSpan(0, 8, 0, 0, 0),
                            Nombre = "Tour a Sídney",
                            PaisID = 14,
                            Precio = 700.00m,
                            TourID = 0
                        },
                        new
                        {
                            ID = 15,
                            DestinoID = 15,
                            FechaInicio = new DateTime(2025, 8, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HoraInicio = new TimeSpan(0, 10, 30, 0, 0),
                            Nombre = "Tour a Pekín",
                            PaisID = 15,
                            Precio = 500.00m,
                            TourID = 0
                        },
                        new
                        {
                            ID = 16,
                            DestinoID = 16,
                            FechaInicio = new DateTime(2025, 8, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HoraInicio = new TimeSpan(0, 9, 0, 0, 0),
                            Nombre = "Tour a Nueva Delhi",
                            PaisID = 16,
                            Precio = 420.00m,
                            TourID = 0
                        },
                        new
                        {
                            ID = 17,
                            DestinoID = 17,
                            FechaInicio = new DateTime(2025, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HoraInicio = new TimeSpan(0, 7, 30, 0, 0),
                            Nombre = "Tour a Atenas",
                            PaisID = 17,
                            Precio = 460.00m,
                            TourID = 0
                        },
                        new
                        {
                            ID = 18,
                            DestinoID = 18,
                            FechaInicio = new DateTime(2025, 8, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HoraInicio = new TimeSpan(0, 8, 30, 0, 0),
                            Nombre = "Tour a Ciudad del Cabo",
                            PaisID = 18,
                            Precio = 380.00m,
                            TourID = 0
                        },
                        new
                        {
                            ID = 19,
                            DestinoID = 19,
                            FechaInicio = new DateTime(2025, 8, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HoraInicio = new TimeSpan(0, 9, 0, 0, 0),
                            Nombre = "Tour a Cartagena",
                            PaisID = 19,
                            Precio = 260.00m,
                            TourID = 0
                        },
                        new
                        {
                            ID = 20,
                            DestinoID = 20,
                            FechaInicio = new DateTime(2025, 8, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HoraInicio = new TimeSpan(0, 10, 0, 0, 0),
                            Nombre = "Tour a Cuzco",
                            PaisID = 20,
                            Precio = 310.00m,
                            TourID = 0
                        });
                });

            modelBuilder.Entity("AgenciaDeDavid.Models.Destino", b =>
                {
                    b.HasOne("AgenciaDeDavid.Models.Pais", "Pais")
                        .WithMany()
                        .HasForeignKey("PaisID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pais");
                });

            modelBuilder.Entity("AgenciaDeDavid.Models.Tour", b =>
                {
                    b.HasOne("AgenciaDeDavid.Models.Destino", "Destino")
                        .WithMany("Tours")
                        .HasForeignKey("DestinoID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AgenciaDeDavid.Models.Pais", "Pais")
                        .WithMany("Tours")
                        .HasForeignKey("PaisID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Destino");

                    b.Navigation("Pais");
                });

            modelBuilder.Entity("AgenciaDeDavid.Models.Destino", b =>
                {
                    b.Navigation("Tours");
                });

            modelBuilder.Entity("AgenciaDeDavid.Models.Pais", b =>
                {
                    b.Navigation("Tours");
                });
#pragma warning restore 612, 618
        }
    }
}
